server:
  port: 9090

spring:
  application:
    name: 251DSWSpringMSDemo01Course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://137.184.120.127:5432/coursesDb
    username: modulo4
    password: modulo4
  jpa:
    hibernate:
      #ddl-auto: create-drop
    #database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka