#spring.application.name=251DSWSpringMSDemo01Eureka
server:
  port: 8761

spring:
  application:
    name: 251DSWSpringMSDemo01Eureka
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serverUrl:
      defaultzone: http://localhost:${server.port}/eureka/
